apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  # Define your configuration data here
  DATABASE_URL: "postgres://username:password@hostname:5432/mydatabase"
  API_KEY: "your-api-key"
  ENVIRONMENT: "production"
  DEBUG_MODE: "false"
